### PR TITLE
Support nginx stream module for tcp load balancer

### PR DESCRIPTION
**Pull request by matsumoto-r**
ngx_mruby will support nginx stream module for tcp load balancer.

I want to control upstream ip-address by each remote ip-address with mruby.

- [x] support mruby for nginx stream feature
- [x] create `Nginx::Stream` class
- [x] create `Nginx::Stream::Connection` class
- [x] create `nginx::Stream::Connection#{upstream_server,upstream_server=}` methods
- [x] fixup code and version compatibility

- configuration concept

```nginx
stream {
  upstream dynamic_server {
    server dev.matsumoto-r.jp:80;
  }
  server {
      listen 12345;
      mruby_stream '
        c = Nginx::Stream::Connection.new "dynamic_server"
        p Nginx::Stream.module_name
        Nginx::Stream.log Nginx::Stream::LOG_NOTICE, "error log dayo"
        Nginx::Stream.log Nginx::Stream::LOG_NOTICE, "remote_ip=#{c.remote_ip}"
        Nginx::Stream.log Nginx::Stream::LOG_NOTICE, "upstream_server=#{c.upstream_server}"
        c.upstream_server = "133.242.179.149:80"
        Nginx::Stream.log Nginx::Stream::LOG_NOTICE, "upstream_server=#{c.upstream_server}"
      ';
      proxy_pass dynamic_server;
  }
}
```

### CODE REVIEW

**Comment by matsumoto-r** [comment]
```
stream {
    server {
        listen 12345;
        mruby_stream 'p "hogehoge"';
        proxy_pass dev.matsumoto-r.jp:80;
    }
}
```

```
 curl http://127.0.0.1:12345/

hello
```

```
2015/10/30 19:57:49 [info] 86074#0: *1 client 127.0.0.1:55615 connected to 0.0.0.0:12345
"hogehoge"
2015/10/30 19:57:49 [info] 86074#0: *1 proxy 192.168.75.101:55616 connected to 210.138.157.8:80
2015/10/30 19:57:49 [info] 86074#0: *1 client disconnected, bytes from/to client:79/272, bytes from/to upstream:272/79
```

**Comment by matsumoto-r** [comment]
```nginx
stream {
    server {
        listen 12345;
        mruby_stream '

p "hogehoge"
p Nginx::Stream.module_name
Nginx::Stream.log Nginx::Stream::LOG_NOTICE, "error log dayo"
Nginx::Stream.log Nginx::Stream::LOG_NOTICE, "remote_ip=#{Nginx::Stream::Connection.new.remote_ip}"

';
        proxy_pass dev.matsumoto-r.jp:80;
    }
}
```

```
2015/10/30 21:48:10 [info] 12183#0: *1 client 127.0.0.1:59768 connected to 0.0.0.0:12345
"hogehoge"
"ngx_mruby-stream-module"
2015/10/30 21:48:10 [notice] 12183#0: *1 error log dayo while initializing connection, client: 127.0.0.1, server: 0.0.0.0:12345
2015/10/30 21:48:10 [notice] 12183#0: *1 remote_ip=127.0.0.1 while initializing connection, client: 127.0.0.1, server: 0.0.0.0:12345
2015/10/30 21:48:10 [info] 12183#0: *1 proxy 192.168.75.101:59769 connected to 210.138.157.8:80
2015/10/30 21:48:10 [info] 12183#0: *1 client disconnected, bytes from/to client:79/272, bytes from/to upstream:272/79
```

**Comment by matsumoto-r** [comment]
- nginx.conf

```nginx
stream {
  upstream dynamic_server {
    server dev.matsumoto-r.jp:80;
  }
  server {
      listen 12345;
      mruby_stream '
        c = Nginx::Stream::Connection.new "dynamic_server"
        p Nginx::Stream.module_name
        Nginx::Stream.log Nginx::Stream::LOG_NOTICE, "error log dayo"
        Nginx::Stream.log Nginx::Stream::LOG_NOTICE, "remote_ip=#{c.remote_ip}"
        Nginx::Stream.log Nginx::Stream::LOG_NOTICE, "upstream_server=#{c.upstream_server}"
        c.upstream_server = "133.242.179.149:80"
        Nginx::Stream.log Nginx::Stream::LOG_NOTICE, "upstream_server=#{c.upstream_server}"
      ';
      proxy_pass dynamic_server;
  }
}
```

- log

```
2015/11/02 16:36:21 [info] 11079#0: *1 client 127.0.0.1:64729 connected to 0.0.0.0:12345
"ngx_mruby-stream-module"
2015/11/02 16:36:21 [notice] 11079#0: *1 error log dayo while initializing connection, client: 127.0.0.1, server: 0.0.0.0:12345
2015/11/02 16:36:21 [notice] 11079#0: *1 remote_ip=127.0.0.1 while initializing connection, client: 127.0.0.1, server: 0.0.0.0:12345
2015/11/02 16:36:21 [notice] 11079#0: *1 upstream_server=210.138.157.8:80 while initializing connection, client: 127.0.0.1, server: 0.0.0.0:12345
2015/11/02 16:36:21 [notice] 11079#0: *1 upstream_server=133.242.179.149:80 while initializing connection, client: 127.0.0.1, server: 0.0.0.0:12345
2015/11/02 16:36:21 [info] 11079#0: *1 proxy 192.168.0.17:64730 connected to 133.242.179.149:80
2015/11/02 16:36:21 [info] 11079#0: *1 client disconnected, bytes from/to client:79/71267, bytes from/to upstream:71267/79
```

**Comment by matsumoto-r** [comment]
## memory conumption

```nginx
stream {
  upstream dynamic_server0 {
    server 127.0.0.1:58080;
  }
  upstream dynamic_server1 {
    server 127.0.0.1:58081;
  }

  server {
      listen 12346;
      mruby_stream_code '
        c = Nginx::Stream::Connection.new "dynamic_server0"
        c.upstream_server = "127.0.0.1:58081"
      ';
      proxy_pass dynamic_server0;
  }

  # test for dynamic tcp load balancer
  # upstream changed from 127.0.0.1:58081 to 127.0.0.1:58080 in mruby
  server {
      listen 12345;
      # cached only
      mruby_stream build/nginx/html/stream_lb.rb;
      proxy_pass dynamic_server1;
  }
}
```

- `build/nginx/html/stream_lb.rb`
```ruby
c = Nginx::Stream::Connection.new "dynamic_server1"
c.upstream_server = "127.0.0.1:58080"
```

### `mruby_stream`(file based)
- startup

```
USER              PID  %CPU %MEM      VSZ    RSS   TT  STAT STARTED      TIME COMMAND
matsumoto_r     38034   0.0  0.0  2466684   5360 s010  S+    6:17PM   0:00.03 ./build/nginx/sbin/nginx
```

- `ab -k -c 10 -n 100000 http://127.0.0.1:12345/mruby`

```
matsumoto_r     38034   0.0  0.0  2466684   6392 s010  S+    6:17PM   0:05.92 ./build/nginx/sbin/nginx
```

- more `ab -k -c 10 -n 100000 http://127.0.0.1:12345/mruby`

```
matsumoto_r     38034   0.0  0.0  2466684   6604 s010  S+    6:17PM   0:11.83 ./build/nginx/sbin/nginx
```

### `mruby_stream_code`(inline code based)
- startup

```
matsumoto_r     38047   0.0  0.0  2465660   5404 s010  S+    6:20PM   0:00.02 ./build/nginx/sbin/nginx
```

- `ab -k -c 10 -n 100000 http://127.0.0.1:12346/`

```
matsumoto_r     38047   0.0  0.0  2465660   6504 s010  S+    6:20PM   0:04.22 ./build/nginx/sbin/nginx
```

- more `ab -k -c 10 -n 100000 http://127.0.0.1:12346/`

```
matsumoto_r     38047   1.8  0.0  2465660   6696 s010  S+    6:20PM   0:08.38 ./build/nginx/sbin/nginx
```

**Comment by chinajinhongyu** [comment]
Hi:
the c.upstream_server could be changed only once when nginx start ?
I want to change the proxy_pass every request, how to do it?

when I use the nginx.conf like the below and the string "TEST TEST TEST TEST" only appeared once in the nginx log;

`  server {
      listen 12346;
      mruby_stream_code '
        c = Nginx::Stream::Connection.new "dynamic_server0"
        c.upstream_server = "127.0.0.1:8888"
	Nginx::Stream.log Nginx::Stream::LOG_NOTICE, "TEST TEST TEST TEST"
      ';
      proxy_pass dynamic_server0;
  }`

I want to change the proxy_pass every request.

**Comment by matsumotory** [comment]
Thank you for your question.

ngx_mruby can change the proxy_pass every request. For example:

```
{
  "server001.phy.exmaple.jp": {
    "stream": [
      "fng001.phy.exmaple.jp:12345",
      "fng001.phy.exmaple.jp:12346"
    ],
    "http": [
      "fng001.phy.exmaple.jp:80"
    ]
  },
  "server002.phy.example.jp": {
    "stream": [
      "fng002.phy.example.jp:12345"
    ],
    "http": [
      "fng001.phy.example.jp:80"
    ]
  }
}
```

```
stream {
  mruby_stream_worker_init_code '
    Userdata.new.server_map = JSON.parse(open("/path/to/server_map.json", &:read))
  ';

  upstream dynamic_fng {
    # dummy address
    server 127.0.0.1: 24224;
  }

  server {
    listen fng-proxy.phy.exmaple.jp:24224;
    mruby_stream_code '
      c = Nginx::Stream::Connection.new("dynamic_fng")
      map = Userdata.new.server_map
      remote_host = c.remote_ip
      upstreams = map[remote_host]["stream"]
      c.upstream_server = upstreams[rand(upstreams.length)]
    ';
    proxy_pass dynamic_fng;
  }
}
```

ref: http://hb.matsumoto-r.jp/entry/2015/11/04/155848

**Comment by chinajinhongyu** [comment]
Hello, thanks for your reply.
I just tried it, it works.
This is my conf file:
```
stream {
  upstream dynamic_fng {
    server 127.0.0.1:3128;
  }
  mruby_stream_init_worker_code '
    Userdata.new.server_map = JSON.parse(open("/data/nginxmtest/ngx_mruby/server_map.json", &:read))
  ';
  mruby_stream_exit_worker_code '
    p "ngx_mruby: STREAM: mruby_stream_exit_worker_code"
  ';

  server {
      listen 12346;
      mruby_stream_code '
	c = Nginx::Stream::Connection.new("dynamic_fng")
        map = Userdata.new.server_map
        remote_host = c.remote_ip
        upstreams = map[remote_host]["stream"]
        c.upstream_server = upstreams[rand(upstreams.length)]
	Nginx::Stream.log Nginx::Stream::LOG_NOTICE, "TEST TEST TEST TEST "
      ';
      proxy_pass dynamic_fng;
  }
}
```
I have some other questions:
When I modify the file "server_map.json", must I restart or reload the Nginx?
I want to change the c.upstream_server dynamicly (add or delete servers) without restart nginx.
Now I want to try read upstream_server conf from redis or file realtime via mruby_stream_code,
but I see the log string "TEST TEST TEST TEST" only appeared once when the nginx start, so I want to know if the mruby_stream_code execute erery request ? or only run once when nginx start.
When I use ngx_lua(https://github.com/openresty/stream-lua-nginx-module), the log appeared every request.

thank you.

**Comment by matsumotory** [comment]
mruby_stream_code execute every request.

**Comment by chinajinhongyu** [comment]
but the code
`Nginx::Stream.log Nginx::Stream::LOG_NOTICE, "TEST TEST TEST TEST "`
seems only run once? does it matter?

**Comment by matsumotory** [comment]
- nginx.conf

```
stream {
  upstream dynamic_server0 {
    server 127.0.0.1:58080;
  }

  server {
      listen 12346;
      mruby_stream_code '
        c = Nginx::Stream::Connection.new "dynamic_server0"
        # get from mruby_stream_init
        c.upstream_server = Userdata.new.new_upstream
        Nginx::Stream.log Nginx::Stream::LOG_NOTICE, "TEST TEST TEST TEST"
      ';
      proxy_pass dynamic_server0;
  }
```

- curl

```
curl 127.0.0.1:12346
curl 127.0.0.1:12346
curl 127.0.0.1:12346
curl 127.0.0.1:12346
```

- logs

```
2017/09/07 15:48:01 [info] 19429#0: *1 client 127.0.0.1:37792 connected to 0.0.0.0:12346
2017/09/07 15:48:01 [notice] 19429#0: *1 TEST TEST TEST TEST while initializing session, client: 127.0.0.1, server: 0.0.0.0:12346
2017/09/07 15:48:01 [info] 19429#0: *1 proxy 127.0.0.1:36508 connected to 127.0.0.1:58081
2017/09/07 15:48:01 [info] 19429#0: *3 hooked mruby inline content code: Nginx.rputs 'proxy test ok', client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", host: "127.0.0.1:12346"
2017/09/07 15:48:01 [info] 19429#0: *1 client disconnected, bytes from/to client:79/135, bytes from/to upstream:135/79
2017/09/07 15:48:01 [info] 19429#0: *3 client 127.0.0.1 closed keepalive connection
2017/09/07 15:48:01 [info] 19429#0: *4 client 127.0.0.1:37796 connected to 0.0.0.0:12346
2017/09/07 15:48:01 [notice] 19429#0: *4 TEST TEST TEST TEST while initializing session, client: 127.0.0.1, server: 0.0.0.0:12346
2017/09/07 15:48:01 [info] 19429#0: *4 proxy 127.0.0.1:36512 connected to 127.0.0.1:58081
2017/09/07 15:48:01 [info] 19429#0: *6 hooked mruby inline content code: Nginx.rputs 'proxy test ok', client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", host: "127.0.0.1:12346"
2017/09/07 15:48:01 [info] 19429#0: *4 client disconnected, bytes from/to client:79/135, bytes from/to upstream:135/79
2017/09/07 15:48:01 [info] 19429#0: *6 client 127.0.0.1 closed keepalive connection
2017/09/07 15:48:01 [info] 19429#0: *7 client 127.0.0.1:37800 connected to 0.0.0.0:12346
2017/09/07 15:48:01 [notice] 19429#0: *7 TEST TEST TEST TEST while initializing session, client: 127.0.0.1, server: 0.0.0.0:12346
2017/09/07 15:48:01 [info] 19429#0: *7 proxy 127.0.0.1:36516 connected to 127.0.0.1:58081
2017/09/07 15:48:01 [info] 19429#0: *9 hooked mruby inline content code: Nginx.rputs 'proxy test ok', client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", host: "127.0.0.1:12346"
2017/09/07 15:48:01 [info] 19429#0: *7 client disconnected, bytes from/to client:79/135, bytes from/to upstream:135/79
2017/09/07 15:48:01 [info] 19429#0: *9 client 127.0.0.1 closed keepalive connection
2017/09/07 15:48:02 [info] 19429#0: *10 client 127.0.0.1:37804 connected to 0.0.0.0:12346
2017/09/07 15:48:02 [notice] 19429#0: *10 TEST TEST TEST TEST while initializing session, client: 127.0.0.1, server: 0.0.0.0:12346
2017/09/07 15:48:02 [info] 19429#0: *10 proxy 127.0.0.1:36520 connected to 127.0.0.1:58081
2017/09/07 15:48:02 [info] 19429#0: *12 hooked mruby inline content code: Nginx.rputs 'proxy test ok', client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", host: "127.0.0.1:12346"
2017/09/07 15:48:02 [info] 19429#0: *10 client disconnected, bytes from/to client:79/135, bytes from/to upstream:135/79
2017/09/07 15:48:02 [info] 19429#0: *12 client 127.0.0.1 closed keepalive connection
2017/09/07 15:48:02 [info] 19429#0: *13 client 127.0.0.1:37808 connected to 0.0.0.0:12346
```

**Comment by chinajinhongyu** [comment]
May be my environmental problems or compile wrong, 
I will rebuld and install and try it.
thank you :+1:

**Comment by matsumotory** [comment]
You are welcome!! :)

**Pull request merged**
