### PR TITLE
Make this build on NetBSD.

### PR DESCRIPTION
**Pull request by yyamano**

### CODE REVIEW

**Comment by matsumoto-r** [comment]
oh, already failed.

**Comment by yyamano** [comment]
I took a look the changes and the travis log, but I have no idea what is wrong. Will try it on Linux later.

**Comment by matsumoto-r** [comment]
fm... it's strange than the following error occurred:

```
curl: /usr/local/lib/libssl.so.1.0.0: no version information available (required by /usr/lib/x86_64-linux-gnu/libcurl.so.4)
curl: /usr/local/lib/libssl.so.1.0.0: no version information available (required by /usr/lib/x86_64-linux-gnu/libcurl.so.4)
curl: /usr/local/lib/libcrypto.so.1.0.0: no version information available (required by /usr/lib/x86_64-linux-gnu/libcurl.so.4)
```

**Comment by yyamano** [comment]
I can't reproduce it on CentOS 7.2. 

> curl: /usr/local/lib/libssl.so.1.0.0: no version information available (required by /usr/lib/x86_64-linux-gnu/libcurl.so.4)

You can see same messages on successful build. (e.g. https://travis-ci.org/matsumoto-r/ngx_mruby/jobs/149922866)

**Comment by yyamano** [comment]
I compared travis log between the last successful build and the failed one.

Travis build system seems to be upgraded. Not sure if it breaks build.

```
-Description:   Ubuntu 14.04.3 LTS
+Description:   Ubuntu 14.04.4 LTS
```

```
-gcc (Ubuntu 4.8.4-2ubuntu1~14.04) 4.8.4
[snip]
+gcc (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4
```

**Comment by yyamano** [comment]
Hmm, I can't reproduce it on Ubuntu 14.04.5.

**Comment by matsumoto-r** [comment]
I confirm the PR pass the test locally. So, I merged now. Thanks!

**Pull request merged**
