### PR TITLE
Make it possible to use Rack based API for error pages to fix #179

### LINKED ISSUE #179: Proposal for Rack based API change for error pages
I'd like to use Rack based API for an error page as below.

```
location /api {
  error_page 401 @error;
  mruby_access_handler /opt/nginx/lib/mruby/auth.rb;
  proxy_pass http://localhost:4567/hello;
}
location @error {
  mruby_content_handler /opt/nginx/lib/mruby/error.rb;
}
```

```
class ErrorResponse
  def call(env)
    return [401, [], ["Unauthorized"]]
  end
end
run ErrorResponse.new
```

It doesn't work as I expected. I get nginx's default error page.

The current implementation calls Nginx.return with a status returned by "call" method.
https://github.com/matsumoto-r/ngx_mruby/blob/master/mrbgems/rack-based-api/mrblib/rack.rb#L90
In my observation, the call causes special response handling for 401 again.

So I’d like to propose to change rack.rb as follows. With this change, 'return [nil, [], ["Unauthorized"]]' works well to me.

```
diff --git a/mrbgems/rack-based-api/mrblib/rack.rb b/mrbgems/rack-based-api/mrblib/rack.rb
index 3ec7c01..57498b4 100644
--- a/mrbgems/rack-based-api/mrblib/rack.rb
+++ b/mrbgems/rack-based-api/mrblib/rack.rb
@@ -75,6 +75,8 @@ module Kernel
     end
 
     def self.build_response r, res
+      return if res.nil?
+
       if res[1].kind_of?(Hash)
         res[1].keys.each { |k| r.headers_out[k] = res[1][k] }
       elsif res[1].kind_of?(Array)
@@ -87,7 +89,7 @@ module Kernel
       else
         raise TypeError, "response body arg type must be Array"
       end
-      Server.return res[0].to_i
+      Server.return res[0].to_i if res[0]
     end
   end

```

### PR DESCRIPTION
**Pull request by yyamano**

### CODE REVIEW

**Comment by matsumoto-r** [comment]
Oh, CI was failed. I'll run again.

**Comment by yyamano** [comment]
I can reproduce it with nginx 1.8.1 on my dev vagrant box. Any idea?

```
Fail: ngx_mruby - ssl certificate changing using data instead of file
 - Assertion[2] Failed: Expected to be equal
    Expected: "1"
      Actual: "0"
```

**Comment by yyamano** [comment]
@matsumoto-r Might it be a timing issue?
Test results are not stable and the test is passed with the following change.

```
diff --git a/test/t/ngx_mruby.rb b/test/t/ngx_mruby.rb
index 75023cf..84d9ae4 100644
--- a/test/t/ngx_mruby.rb
+++ b/test/t/ngx_mruby.rb
@@ -406,6 +406,7 @@ end
 t.assert('ngx_mruby - ssl certificate changing using data instead of file') do
   res = `curl -k #{base_ssl(58083) + '/'}`
   t.assert_equal 'ssl test ok', res
+  dummy = `curl -k #{base_ssl(58083) + '/'}`
   res = `openssl s_client -servername localhost -connect localhost:58083 < /dev/null 2> /dev/null | openssl x509 -text  | grep Not | sed -e "s/://" | awk '{print (res = $6 - res)}' | tail -n 1`.chomp
   t.assert_equal "1", res
   res = `openssl s_client -servername hogehoge -connect 127.0.0.1:58083 < /dev/null 2> /dev/null | openssl x509 -text  | grep Not`.chomp
```

**Comment by matsumoto-r** [comment]
@yyamano fmm... Do you understand the root cause?

**Comment by yyamano** [comment]
@matsumoto-r I think the problem comes from https://github.com/matsumoto-r/ngx_mruby/blob/master/src/http/ngx_http_mruby_ssl.c#L60

mscf->cert_data.data points to internal representation of mruby's String that might be GC'ed.
I compiled mruby with GC_DEBUG and GC_PROFILE. The test failed only after GC.
Also the problem seems to be gone with the following change.

```
diff --git a/src/http/ngx_http_mruby_ssl.c b/src/http/ngx_http_mruby_ssl.c
index f6026c4..01081d0 100644
--- a/src/http/ngx_http_mruby_ssl.c
+++ b/src/http/ngx_http_mruby_ssl.c
@@ -55,9 +55,12 @@ static mrb_value ngx_mrb_ssl_set_cert_data(mrb_state *mrb, mrb_value self)
   ngx_http_mruby_srv_conf_t *mscf = mrb->ud;
   char *data;
   mrb_int data_len;
+  char *s;
 
   mrb_get_args(mrb, "s", &data, &data_len);
-  mscf->cert_data.data = (u_char *)data;
+  s = malloc(data_len + 1); /* leak */
+  strcpy(s, data);
+  mscf->cert_data.data = (u_char *)s;
   mscf->cert_data.len = data_len;
 
   return mrb_str_new(mrb, (char *)mscf->cert_data.data, mscf->cert_data.len);
@@ -68,9 +71,12 @@ static mrb_value ngx_mrb_ssl_set_cert_key_data(mrb_state *mrb, mrb_value self)
   ngx_http_mruby_srv_conf_t *mscf = mrb->ud;
   char *data;
   mrb_int data_len;
+  char *s;
 
   mrb_get_args(mrb, "s", &data, &data_len);
-  mscf->cert_key_data.data = (u_char *)data;
+  s = malloc(data_len + 1); /* leak */
+  strcpy(s, data);
+  mscf->cert_key_data.data = (u_char *)s;
   mscf->cert_key_data.len = data_len;
 
   return mrb_str_new(mrb, (char *)mscf->cert_key_data.data, mscf->cert_key_data.len);
```

I have no idea how to fix it cleanly. Using malloc/free is kinda pain:-<

**Comment by matsumoto-r** [comment]
@yyamano Thank you for your investigation. I'll also investigate it.

**Comment by matsumoto-r** [comment]
@yyamano I have written the patch for the unexpected gc issue via #181 . Please apply the patch and try to check this PR again.

**Comment by yyamano** [comment]
Thank you so much. I will try it next week. I will be mostly AFK for the rest of this week.

**Comment by matsumoto-r** [comment]
Thanks!!

**Pull request merged**
