### PR TITLE
Enable to use mruby_access_handler in server scope.

### PR DESCRIPTION
**Pull request by yyamano**

### CODE REVIEW

**Comment by yyamano** [comment]
The root cause of the build errors on travis is the latest version of mruby-redis. https://github.com/matsumoto-r/mruby-redis/issues/62

But ngx_mruby build system is broken too. I'm fixing it.

**Comment by yyamano** [comment]
@matsumoto-r Could you trigger a travis build? It's an external problem.

```
$ curl -L https://www.openssl.org/source/openssl-1.0.2-latest.tar.gz > openssl-1.0.2.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   323  100   323    0     0    816      0 --:--:-- --:--:-- --:--:--   815

[snip]

curl: (47) Maximum (50) redirects followed
```

**Comment by matsumoto-r** [comment]
I reran the travls ci.

**Comment by matsumoto-r** [comment]
Just now the openssl site has the recursive redirect problem. Please check it later.

**Comment by yyamano** [comment]
Sure. Thank you for taking your time.

**Comment by matsumoto-r** [comment]
I also confirm the PR pass the test locally. So, I merged now. Thanks!

Then, we should investigate and fix travis configuration on #203 or other PRs.

**Pull request merged**
