### PR TITLE
Added `--with-openssl-src` to configure script

### PR DESCRIPTION
**Pull request by rhykw**
refs: #165 

To build mrbgems and nginx with same openssl.

usage:

```sh
./configure \
--with-openssl-src=$HOME/tmp/openssl-1.0.2g \
--with-openssl-opt="no-zlib" \
--with-ngx-src-root=$HOME/tmp/nginx-1.9.15 \
--with-ngx-config-opt="--prefix=/usr/local --with-http_ssl_module"

make
```

### CODE REVIEW

**Comment by matsumoto-r** [comment]
@rhykw Thank you for your PR. I have some questions.

- Did you consider ngx_mruby don't use mruby-digest?
- This PR supports some build process like [this](https://github.com/matsumoto-r/ngx_mruby/wiki/Install#2-build)?
- How dose mruby-digest find correct path of openssl library don't change the mruby-digest/mrbgem.rake?

**Comment by rhykw** [comment]
@matsumoto-r 

> * Did you consider ngx_mruby don't use mruby-digest?
> * How dose mruby-digest find correct path of openssl library don't change the mruby-digest/mrbgem.rake?


GCC is searching libraries in LDFLAGS and CFLAGS.

in *mruby/tasks/toolchains/gcc.rake*
```
    cc.flags = [ENV['CFLAGS'] || %w(-g -std=gnu99 -O3 -Wall -Werror-implicit-function-declaration -Wdeclaration-after-statement -Wwrite-strings)]
    linker.flags = [ENV['LDFLAGS'] || %w()]
```

----

> * This PR supports some build process like this?

usage with build.sh:

```sh
NGINX_CONFIG_OPT_ENV='--prefix=/usr/local/nginx --with-http_ssl_module' \ NGINX_SRC_ENV=$HOME/tmp/nginx-1.9.15 \
sh build.sh --with-openssl-src=$HOME/tmp/openssl-1.0.2g --with-openssl-opt="no-zlib"
```

**Comment by rhykw** [comment]
I wrote a test shell script for #165 
https://gist.github.com/rhykw/b7d10721937fab08c6d17890a7afa61c

Not added `--with-openssl-src` caused segmentation fault.
https://gist.github.com/rhykw/b7d10721937fab08c6d17890a7afa61c#gistcomment-1761083

Added  `--with-openssl-src` not caused segmentation fault.
https://gist.github.com/rhykw/b7d10721937fab08c6d17890a7afa61c#gistcomment-1761091

**Comment by matsumoto-r** [comment]
Great works!! Merged now.

**Pull request merged**
